=== nd524s/Parser_XML/out/artifacts/Servlet_war_exploded/resources/old-cards.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/cards"
        xmlns:tns="http://www.example.com/cards"
        elementFormDefault="qualified">
    <element name="card" type="tns:CardType" abstract="true"></element>
    <element name="greeting-card" type="tns:GreetingCard" substitutionGroup="tns:card"></element>
    <element name="promotional-card" type="tns:PromotionalCard" substitutionGroup="tns:card"></element>
    <element name="music-card" type="tns:MusicCard" substitutionGroup="tns:card"></element>
    
    <element name="cards">
        <complexType>
            <sequence>
                <element ref="tns:card" minOccurs="0" maxOccurs="unbounded"></element>
            </sequence>
        </complexType>
    </element>

    <complexType name="CardType">
        <sequence>
            <element name="year" type="string" />
            <element name="thema" type="string" />
            <element name="sending" type="boolean" />
            <element name="country" type="string" />
            <element name="valuable" type="tns:Valuable" />
        </sequence>
    </complexType>

    <complexType name="GreetingCard">
        <complexContent>
            <extension base="tns:CardType">
                <sequence>
                    <element name="author" type="tns:Author" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="PromotionalCard">
        <complexContent>
            <extension base="tns:CardType">
                <sequence>
                    <element name="company-name" type="string" />
                </sequence>
                <attribute name="advertising-phone" type="integer" use="required"></attribute>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="MusicCard">
        <complexContent>
            <extension base="tns:CardType">
                <sequence>
                    <element name="author" type="tns:Author" />
                    <element name="song" type="string" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Author">
        <sequence>
            <element name="name" type="string" />
            <element name="birth-date" type="tns:Year" />
            <element name="birth-place" type="string" />
        </sequence>
    </complexType>

    <simpleType name="Year">
        <restriction base="string">
            <pattern value="(0?[1-9]|[12][0-9]|3[01])\.(0?[1-9]|1[012])\.((18|19|20)\d\d)" />
        </restriction>
    </simpleType>

    <simpleType name="Valuable">
        <restriction base="string">
            <enumeration value="historical"></enumeration>
            <enumeration value="collectional"></enumeration>
            <enumeration value="thematic"></enumeration>
        </restriction>
    </simpleType>
</schema>

=== nd524s/Parser_XML/out/artifacts/Servlet_war_exploded/resources/cards.xml
<?xml version="1.0" encoding="UTF-8"?>
<cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.example.com/cards"
       xsi:schemaLocation="http://www.example.com/cards old-cards.xsd">
    <promotional-card advertising-phone="1947248">
        <year>1939</year>
        <thema>clothes</thema>
        <sending>false</sending>
        <country>France</country>
        <valuable>collectional</valuable>
        <company-name>Gucci</company-name>
    </promotional-card>
    <greeting-card>
        <year>1901</year>
        <thema>nature</thema>
        <sending>false</sending>
        <country>Russia</country>
        <valuable>historical</valuable>
        <author>
            <name>Nikolay Zinkovich</name>
            <birth-date>15.10.1882</birth-date>
            <birth-place>Russia</birth-place>
        </author>
    </greeting-card>
    <greeting-card>
        <year>1890</year>
        <thema>people</thema>
        <sending>true</sending>
        <country>Russia</country>
        <valuable>historical</valuable>
        <author>
            <name>Vladislav Sichevskiy</name>
            <birth-date>11.08.1810</birth-date>
            <birth-place>Russia</birth-place>
        </author>
    </greeting-card>
    <greeting-card>
        <year>1924</year>
        <thema>nature</thema>
        <sending>false</sending>
        <country>USA</country>
        <valuable>historical</valuable>
        <author>
            <name>John Snow</name>
            <birth-date>15.10.1900</birth-date>
            <birth-place>USA</birth-place>
        </author>
    </greeting-card>
    <greeting-card>
        <year>1970</year>
        <thema>since</thema>
        <sending>false</sending>
        <country>USA</country>
        <valuable>collectional</valuable>
        <author>
            <name>Pavel Dechenya</name>
            <birth-date>12.11.1944</birth-date>
            <birth-place>Germany</birth-place>
        </author>
    </greeting-card>
    <promotional-card advertising-phone="3019911">
        <year>1955</year>
        <thema>building</thema>
        <sending>true</sending>
        <country>Great Britain</country>
        <valuable>collectional</valuable>
        <company-name>Buildgroup</company-name>
    </promotional-card>
    <promotional-card advertising-phone="3023355">
        <year>1968</year>
        <thema>sport</thema>
        <sending>false</sending>
        <country>USA</country>
        <valuable>collectional</valuable>
        <company-name>Nike</company-name>
    </promotional-card>
    <promotional-card advertising-phone="7050817">
        <year>1980</year>
        <thema>sport</thema>
        <sending>true</sending>
        <country>USA</country>
        <valuable>collectional</valuable>
        <company-name>Reebok</company-name>
    </promotional-card>
    <music-card>
        <year>1943</year>
        <thema>architecture</thema>
        <sending>true</sending>
        <country>USSR</country>
        <valuable>thematic</valuable>
        <author>
            <name>Taras Tesler</name>
            <birth-date>15.10.1915</birth-date>
            <birth-place>Ukraine</birth-place>
        </author>
        <song>Vivaldi</song>
    </music-card>
    <music-card>
        <year>1941</year>
        <thema>since</thema>
        <sending>true</sending>
        <country>USSR</country>
        <valuable>thematic</valuable>
        <author>
            <name>Alex Petrushko</name>
            <birth-date>03.06.1900</birth-date>
            <birth-place>Ukraine</birth-place>
        </author>
        <song>Bah</song>
    </music-card>
    <music-card>
        <year>1920</year>
        <thema>nature</thema>
        <sending>true</sending>
        <country>USSR</country>
        <valuable>thematic</valuable>
        <author>
            <name>Vlad Krasov</name>
            <birth-date>03.06.1911</birth-date>
            <birth-place>Belarus</birth-place>
        </author>
        <song>Mozart</song>
    </music-card>
    <music-card>
        <year>1928</year>
        <thema>art</thema>
        <sending>true</sending>
        <country>USSR</country>
        <valuable>collectional</valuable>
        <author>
            <name>Igor Novitski</name>
            <birth-date>09.09.1870</birth-date>
            <birth-place>Russia</birth-place>
        </author>
        <song>Mozart</song>
    </music-card>
</cards>
